version: "3"
services:
  bitmart_download_order_book_and_trades:
    image: hummingbot/hummingbot:latest
    volumes:
      - ./scripts:/home/hummingbot/scripts
      - ./conf:/home/hummingbot/conf
      - ./data/order_book:/home/hummingbot/data
    environment:
        - CONFIG_PASSWORD=a
        - CONFIG_FILE_NAME=download_order_book_and_trades.py
        - EXCHANGE=bitmart_paper_trade
        - TRADING_PAIRS=LINK-USDT,BTC-USDT
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    tty: true
    stdin_open: true
    network_mode: host

  ascendex_download_order_book_and_trades:
    image: hummingbot/hummingbot:latest
    volumes:
      - ./scripts:/home/hummingbot/scripts
      - ./conf:/home/hummingbot/conf
      - ./data/order_book:/home/hummingbot/data
    environment:
      - CONFIG_PASSWORD=a
      - CONFIG_FILE_NAME=download_order_book_and_trades.py
      - EXCHANGE=ascend_ex_paper_trade
      - TRADING_PAIRS=LINK-USDT,BTC-USDT
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    tty: true
    stdin_open: true
    network_mode: host

  binance_download_order_book_and_trades:
    image: hummingbot/hummingbot:latest
    volumes:
      - ./scripts:/home/hummingbot/scripts
      - ./conf:/home/hummingbot/conf
      - ./data/order_book:/home/hummingbot/data
    environment:
      - CONFIG_PASSWORD=a
      - CONFIG_FILE_NAME=download_order_book_and_trades.py
      - EXCHANGE=binance_paper_trade
      - TRADING_PAIRS=LINK-USDT,BTC-USDT
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    tty: true
    stdin_open: true
    network_mode: host