version: "3"
services:
  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb:latest-pg14
    environment:
      - POSTGRES_USER={POSTGRES_USER}
      - POSTGRES_PASSWORD={POSTGRES_PASSWORD}
      - POSTGRES_DB={POSTGRES_DB}
    volumes:
      - timescale-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  optunadb:
    container_name: optunadb
    image: postgres:latest
    environment:
      - POSTGRES_USER={POSTGRES_USER}
      - POSTGRES_PASSWORD={POSTGRES_PASSWORD}
      - POSTGRES_DB={POSTGRES_DB}
    volumes:
      - optuna-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  timescale-data:
    driver: local
  optuna-data:
    driver: local
